import { getDeckBackgroundImage } from "@/lib/gradient-generator";

export interface Deck {
  slug: string;
  title: string;
  description: string;
  createdAt: Date; // Date when the deck was created
  imageUrl?: string; // Optional URL for the deck's homepage image (auto-generated if not provided)
}

export const decks: Deck[] = [
  {
    slug: "example-deck",
    title: "Example Deck",
    description: "A sample presentation deck to demonstrate the system",
    createdAt: new Date("2024-01-15"), // Date when this deck was created
    // imageUrl will be auto-generated by getDeckWithImage() function
  },
  {
    slug: "cursor-llms-product-designer",
    title: "AI Assisted Design Process",
    description: "How to augment your process with LLMs",
    createdAt: new Date("2024-12-20"), // Date when this deck was created
    // imageUrl will be auto-generated by getDeckWithImage() function
  },
  // Add more decks here as you create them
];

/**
 * Get a deck with auto-generated imageUrl if not provided
 * This ensures data URLs are generated fresh and not lost during serialization
 */
export function getDeckWithImage(deck: Deck): Deck {
  return {
    ...deck,
    imageUrl: deck.imageUrl || getDeckBackgroundImage(deck.slug),
  };
}

export function getDeckBySlug(slug: string): Deck | undefined {
  return decks.find((deck) => deck.slug === slug);
}

